name: meet_unicode
description: A task project for DJSCE Unicode 2023.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  get: ^4.6.5
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  package_info_plus: 
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  awesome_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/nunito.ttf
  
